### PR TITLE
added file-loader

### PR DESCRIPTION
**Pull request by ljmerza**
files imported via CSS will throw an error in webpack. Need file-loader to make these work

```
background-image:url('../static/photo.png');
```

### CODE REVIEW

**Comment by erickzhao** [comment]
Hey @ljmerza, thanks for the PR! Do you think that we could add font files to the regex as well? I think that's missing as well.

**Comment by ljmerza** [comment]
Ok I added fonts but kept them in a separate folder

**Comment by erickzhao** [comment]
@ljmerza could you add the newer changes in a separate PR? 🤔

**Comment by ljmerza** [comment]
whoops forgot to make a new branch.

**Comment by ljmerza** [comment]
fixed pr review

**Pull request merged**
